---
- name: Create VLAN and Verify
  hosts: access
  gather_facts: no

  tasks:
    - name: Ping and Register Result
      local_action: command ping -q -c 5 -i .2
      register: ping_result

    - debug:
        msg: "{{ ping_result.stdout_lines }}"
